// <auto-generated />
using System;
using DocumentsApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocumentsApi.Database.Migrations
{
    [DbContext(typeof(DocumentsApiContext))]
    partial class DocumentsApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DocumentsApi.Database.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("19dd725d-d032-413b-bd04-ca89e5c8394b"),
                            DocumentName = "document_instructions",
                            FileName = "document_instructions.docx",
                            FileSize = 2097152L,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("42069b65-489e-4aea-bc8d-320acad1c17b"),
                            DocumentName = "advanced_javascript_practices",
                            FileName = "advanced_javascript_practices.pdf",
                            FileSize = 12097152L,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("8770e755-ea68-4995-8553-a0b49e4f46ba"),
                            DocumentName = "C# 8.0 and .NET Core 3.0",
                            FileName = "C# 8.0 and .NET Core 3.0.docx",
                            FileSize = 22097152L,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("feac3b11-5269-4678-b656-d4fda7c6a889"),
                            DocumentName = "C# in Depth",
                            FileName = "C# in Depth.pdf",
                            FileSize = 32097152L,
                            Version = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
